CREATE TABLE MATCHING_TBL(
MATCHING_NO NUMBER PRIMARY KEY,
MATCHING_CATAGORY VARCHAR2(200) NULL,
MATCHING_GAME VARCHAR2(100),
MATCHING_ID VARCHAR2(50) NOT NULL,
MEMBER_ID VARCHAR2(50) NOT NULL,
MATCHING_GRADE VARCHAR2(50)NOT NULL,
MATCHING_CONTENT VARCHAR2(1000) NOT NULL,
MATCHING_MAXCOUNT  NUMBER NOT NULL,
MATCHING_MINCOUNT  NUMBER DEFAULT 0,
MATCHING_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
UPDATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE SIGNAL_TBL
(SIGNAL_NO NUMBER PRIMARY KEY,
MATCHING_NO NUMBER,
MAIN_ID VARCHAR(50),
APPLICATION_ID VARCHAR(50),
APPLICATION_MESSAGEM VARCHAR(100),
APPLICATION_SITUATION VARCHAR(10),
GAME_SITUATION VARCHAR(10),
REG_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
UPDATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
);